### ISSUE TITLE
always no respond

### ISSUE THREAD

**Issue by james616616** [siutsin/telegram-jung2-bot#10]

**Comment by siutsin** [comment]
Can you provide the details and steps for reproducing this issue?

**Comment by siutsin** [comment]
Alright I can reproduce it now, working on it...

**Comment by james616616** [comment]
always had a ~5mins delay
after the delay, it will respond to all requested command. this may make
the server overload

**Comment by siutsin** [comment]
It turns out that there are too many DB queries and used up all the concurrent connection.
1.1.4 has been deployed and I will keep this issue open and observe for couple days
