### ISSUE TITLE
Can i customized the counting number announcement time? 

### ISSUE THREAD

**Issue by nbapang** [siutsin/telegram-jung2-bot#1759]
Great Bot.
can i customized the counting number announcement time? if no can you see if you can provide me a version where this customization is avaliable? 
my TG: @chung2hk 
Email: ch668877@protonmail.com

**Comment by siutsin** [comment]
I was planning to include the adjustable `offFromWork` feature after a complete rewrite of this project, but it seems I will never have time to do that. I will see what I can do in the current version.

**Comment by siutsin** [comment]
@swhsiang working on it 🙂

**Comment by siutsin** [comment]
Deployed. Sample command:
```
/setOffFromWorkTimeUTC 1800 MON,TUE,WED,THU,FRI
```
Note that the timezone will be UTC.

**Comment by swhsiang** [comment]
thank you for your hard work.
