### ISSUE TITLE
Allow multiple data storage implementations

### ISSUE THREAD

**Issue by nothize** [siutsin/telegram-jung2-bot#26]
Currently, public methods of MessageController are coupled with mongoose dependent methods. It is desirable to extend the storage flexibility to make it easier to switch to or experiment with other data storage facilities or to quickly start the bot (by using sqlite3 or memory cache as the data storage) for a quick preview of the functionalities of the bot.

As discussed with @siutsin , one of a requirement related to this change is to allow certain operations (such as adding a message) to be executed on multiple data storage implementations.

**Comment by siutsin** [comment]
> As discussed with @siutsin , one of a requirement related to this change is to allow certain operations (such as adding a message) to be executed on multiple data storage implementations.

The rationale behind this is for DB migration. If the goal is switching to another DB from mongoDB, or to persist data into several places, a facade layer should be introduced.

![jung2bot-facade](https://cloud.githubusercontent.com/assets/904442/15092844/5ef6227a-14a8-11e6-89d3-b3614ba4e1c4.png)

Please feel free to suggest any other approach.

**Comment by nothize** [comment]
Please review the incomplete draft:

https://github.com/nothize/telegram-jung2-bot/commit/4617a6ec6df8cbd9fbb655890e73ba91c2714440

**Comment by siutsin** [comment]
Currently, cache DB is also using Mongo, which supported by Mongoose with multiple connection
