### ISSUE TITLE
Can i ban /alljung command?

### ISSUE THREAD

**Issue by Tiande** [siutsin/telegram-jung2-bot#41]
/alljung list all members....
How to make nobody to use this command?
Thanks!

**Comment by Tiande** [comment]
> Unfortunately, there is no admin option for now. I am planning for a full revamp and may add this as an option.

Thanks!
And should I close this issue?

**Comment by siutsin** [comment]
Will keep this open for now and re-evaluate once the revamp started. Thanks for the suggestion
