### ISSUE TITLE
Unable to Show Top 10 Members at 18:00

### ISSUE THREAD

**Issue by singledognofrd** [siutsin/telegram-jung2-bot#866]
Sorry I’m new to GitHub but I’m here to report an issue of JungBot. It cannot automatically display top 10 jung people for my group at 18:00 since a few days ago while it works for other groups. I tried kicking and rebooting the bot but the problem still exists. Here is my telegram ID: @Sxiymloenm. Feel free to contact me. Thanks.

**Comment by siutsin** [comment]
@singledognofrd Can you add the testing bot [@test_jung2_bot](https://t.me/test_jung2_bot) to your group? Let's see if there is any discrepancy.

**Comment by singledognofrd** [comment]
Added @test_jung2_bot. Sometimes it worked but sometimes not. It failed to show the list today.

**Comment by siutsin** [comment]
@singledognofrd I manually triggered two `offFromWork` events at around 5 May 9:30 pm HKT for the test bot, and I managed to get both of it. Also, from the log, Telegram shows the messages are delivered successfully. Can you please help to confirm from your end?

**Comment by singledognofrd** [comment]
Confirmed.

**Comment by siutsin** [comment]
@singledognofrd Thanks for the confirmation, I haven't changed anything from my end besides enabling the log.
Please let me know again if the issue happens, and I will dig into the log again.

**Comment by singledognofrd** [comment]
Only the test bot showed the statistics today  (12/5) and the original jung bot didn’t. This is the first time since last comment.

**Comment by siutsin** [comment]
That is very weird. I didn't hear similar issue from other users so far.
I will need some in-depth investigation to see what's going on. Hopefully sometime next week.
